export class pegawaiDinilai {
    nama: string | undefined;
    noKP: string | undefined;
    emel: string | undefined;
    skimPerkhidmatan: string | undefined;
    gredHakiki: string | undefined;
    namaJawatan: string | undefined;
    gredDisandang: string | undefined;
    noFail: string | undefined;
    kementerian: string | undefined;
    tarikhMulaKontrak: Date | undefined;
    tarikhAkhirKontrak: Date | undefined;
    tempatBertugas: number | undefined;
    idUnit: string | undefined;
    idSktTerkini?: number | undefined;
    tahunPenilaianTerkini: number | undefined;
    kategoriPenilaianTerkini: string | undefined;
    statusPenilaianTerkini: string | undefined;
    idBahagian: string | undefined;
    isActive: boolean | undefined;
    status?: string;
    buttonOption?: string;
    id?: number;
    gambar?: string;
    // details?: { label: string; label2: string }[];
    details?: string;
    namaPPP: string | undefined;
    namaPPK: string | undefined;
    idPPP?: number;
    namaBahagian: string | undefined;
    namaUnit: string | undefined;
    jawatanPPP: string | undefined;
    gredPPP: string | undefined;
    idBahagianPPP: string | undefined;
    idUnitPPP: string | undefined;
    bahagianPPP: string | undefined;
    unitPPP: string | undefined;
    jawatanPPK: string | undefined;
    gredPPK: string | undefined;
    idBahagianPPK: string | undefined;
    idUnitPPK: string | undefined;
    bahagianPPK: string | undefined;
    unitPPK: string | undefined;
    _busy?: boolean;
}
